ndk

diff --git a/config b/config
--- a/config
+++ b/config
@@ -1,25 +1,21 @@
-#if test -n "$ngx_module_link"; then
-#    if test -n "$NDK_SRCS"; then
-#        echo "found ngx_devel_kit for ngx_form_input; looks good."
-#    else
-#        echo "error: ngx_devel_kit is required to build ngx_form_input; please put it before ngx_form_input." 1>&2
-#        exit 1
-#    fi
-#else
-#    if echo $HTTP_MODULES | grep " ndk_http_module" > /dev/null; then
-#        echo "found ngx_devel_kit for ngx_form_input; looks good."
-#    else
-#        echo "error: ngx_devel_kit is required to build ngx_form_input; please put it before ngx_form_input." 1>&2
-#        exit 1
-#    fi
-#fi
+if test -n "$ngx_module_link"; then
+    if test -n "$NDK_SRCS"; then
+        echo "found ngx_devel_kit for ngx_form_input; looks good."
+    else
+        echo "error: ngx_devel_kit is required to build ngx_form_input; please put it before ngx_form_input." 1>&2
+        exit 1
+    fi
+else
+    if echo $HTTP_MODULES | grep " ndk_http_module" > /dev/null; then
+        echo "found ngx_devel_kit for ngx_form_input; looks good."
+    else
+        echo "error: ngx_devel_kit is required to build ngx_form_input; please put it before ngx_form_input." 1>&2
+        exit 1
+    fi
+fi
 
-HTTP_FORM_INPUT_SRCS="                                                      \
-                    $ngx_addon_dir/src/ngx_http_form_input_module.c         \
-                    "
-HTTP_FORM_INPUT_DEPS="                                                      \
-                    $ngx_addon_dir/src/ddebug.h                             \
-                    "
+HTTP_FORM_INPUT_SRCS="$ngx_addon_dir/src/ngx_http_form_input_module.c"
+HTTP_FORM_INPUT_DEPS="$ngx_addon_dir/src/ddebug.h"
 
 ngx_addon_name=ngx_http_form_input_module
 
@@ -38,3 +34,4 @@ else
     NGX_ADDON_DEPS="$NGX_ADDON_DEPS $HTTP_FORM_INPUT_DEPS"
 fi
 
+CFLAGS="$CFLAGS -DNDK_SET_VAR"
